### ISSUE TITLE
AAS registration numbers broken down by faculty

### ISSUE THREAD

**Issue by ynasser** [uWaterloo/OpenData#103]
I know this is a long shot, especially since AAS (formerly known as ODP: https://uwaterloo.ca/disability-services/) has no data publicly available and is tied down with lots of confidentiality agreements. I'd be willing to contact them to see if they have any data they can release.

Also, title says "registration numbers broken down by faculty," but anything they're willing to release would be helpful.

**Comment by ynasser** [comment]
@nathanv have you followed up yet?

**Comment by ynasser** [comment]
@nathanv ping?

**Comment by nathanv** [comment]
Hello @ynasser Thanks for checking in. I have not followed up. Thanks for pinging. I'm a bit confused reading the previous thread. Is it the case that the AccessAbility office never got back to you?
