### ISSUE TITLE
Data Request: Accounting Flexfield Segment Definitions

### ISSUE THREAD

**Issue by axyjo** [uWaterloo/OpenData#129]
Data available in non-machine-readable format (PDF) here: https://uwaterloo.ca/finance/budgets-client-services/accounting-flexfield-definition

**Comment by axyjo** [comment]
Any updates?

**Comment by axyjo** [comment]
@nathanv bump.

**Comment by colinbellCA** [comment]
We have this data accessible in our business intelligence suite now.  I
have a meeting today and will again attempt to see if we can bring this to
open data.

**Comment by axyjo** [comment]
Bump. @colinbellCA
