### ISSUE TITLE
Stale data for info sessions 

### ISSUE THREAD

**Issue by steviek** [uWaterloo/OpenData#155]
Still returns the data for spring 2014

**Comment by JoeRadman** [comment]
Hi - I'll correct this today. Thanks.

**Comment by JoeRadman** [comment]
I handle the raw feeds - which is consumed by the api - and they look OK. The API may need to be corrected (which is not my area).

**Comment by KartikTalwar** [comment]
Sorry for the late reply @JoeRadman I don't believe we've been setup for an infosession feed. We only have the workshops feed. If I'm mistaken, would it be possible for you to email me the details for the feed (ktalwar@uwaterloo.ca)? 

We've been scraping the current infosession data and I'll have it up for this term asap

**Comment by KartikTalwar** [comment]
The infosession endpoint now includes data from the real CECS feed thanks to @JoeRadman! Historical term data via the same endpoint is also available.
