### ISSUE TITLE
menu_url is incorrect for many FEDS locations

### ISSUE THREAD

**Issue by zachomedia** [uWaterloo/OpenData#157]
The `menu_url` for Wasabi in the [locations endpoint](https://api.uwaterloo.ca/v2/foodservices/locations.json) is incorrect.

````json
{
"outlet_id": 1213,
"outlet_name": "Wasabi",
"building": "SLC",
"logo": "https://pilots.uwaterloo.ca/feds/sites/ca.feds/files/commercial-services-pages-logos-wasabi.png",
"latitude": 43.471541,
"longitude": -80.544806,
"description": "Wasabi! is the Feds' own sushi bar! Assorted varieties of sushi are made fresh daily and all at student-friendly prices! Drop by and give sushi a try.",
"notice": null,
"is_open_now": false,
...,
"additional": {
"menu_url": "http://www.feds.ca/wp-content/blogs.dir/57/files//2012/08/Wasabi-Menu-Theresa.pn..."
}
},
````
 The correct URL is: http://www.feds.ca/wp-content/blogs.dir/57/files//2012/08/Wasabi-Menu-Theresa.png

**Comment by zachomedia** [comment]
Just in case it isn't immediately obvious, the url returned by the endpoint ends with `sa.pn...` whereas the actual ends with `sa.png`

**Comment by KartikTalwar** [comment]
Thanks @zachomedia! Definitely a bug on our end. It's now been fixed :-)

**Comment by zachomedia** [comment]
@KartikTalwar Thanks for the quick fix but this brought up a different issue: now outlets from FEDS that don't have a menu have the following link in the `menu_html` field: https://pilots.uwaterloo.ca/feds/menu (I don't remember them having it before). This URL returns a page not found error.

**Comment by zachomedia** [comment]
@KartikTalwar Looking at old data returned from the API (Jan 23), it looks like those URLs were returned so this may actually be an issue with the source of the data and not the API.

**Comment by KartikTalwar** [comment]
@zachomedia yeah sadly, the source has the url which is a 404. I'll send in the request to have it corrected, hopefully it'll be operational on Monday

**Comment by nathanv** [comment]
Fixed. The sites with a 404 have no menu listed. Also made sure all the hours are up to date.
