### ISSUE TITLE
Additional Information for the /events/ endpoint

### ISSUE THREAD

**Issue by DeonHua** [uWaterloo/OpenData#159]
Currently the `/events/` endpoint provides data as per [this document](https://github.com/uWaterloo/api-documentation/blob/master/v2/events/events.md). Is there any chance we can add event location and descriptions to the provided information?

**Comment by KartikTalwar** [comment]
https://github.com/uWaterloo/api-documentation/blob/master/v2/events/events_site_id.md

**Comment by KartikTalwar** [comment]
I assume you mean adding that info to the /events endpoint itself?

**Comment by DeonHua** [comment]
Yep!
