### ISSUE TITLE
https://api.uwaterloo.ca/v2/foodservices/locations.json returning 500: Internal Server Error

### ISSUE THREAD

**Issue by zachomedia** [uWaterloo/OpenData#161]
https://api.uwaterloo.ca/v2/foodservices/locations.json endpoint is returning 500: Internal Server Error.

Other endpoints appear to be working correctly.

**Comment by KartikTalwar** [comment]
Hey @zachomedia there was a change in the schema we get from upstream and that broken down all the endpoints that rely on datetime. Things are back to normal now
