### ISSUE TITLE
https://api.uwaterloo.ca/v2/foodservices/locations.json only returning Feds locations (missing Food Services locations)

### ISSUE THREAD

**Issue by zachomedia** [uWaterloo/OpenData#162]
https://api.uwaterloo.ca/v2/foodservices/locations.json is currently only returning locations for Feds and is missing the Food Services locations.

https://api.uwaterloo.ca/v2/foodservices/menu.json is only returning Pastry Plus and not the other locations with menus for the week (https://uwaterloo.ca/food-services/menu/2015/13).

**Comment by alykhank** [comment]
+1. I was about to file the same issue, I first saw it on Saturday and hoped it might be a transient data issue but it is still persisting.

**Comment by nathanv** [comment]
Fixed.

**Comment by nathanv** [comment]
@alykhank When you see it, report it! :D. Next person to report a bug first get a free coffee on me! :P.
