### ISSUE TITLE
FoodServices Menu Endpoint Product ID's are reused for different items

### ISSUE THREAD

**Issue by alykhank** [uWaterloo/OpenData#163]
It appears that the product ID field in the FoodServices Menu endpoint data has different corresponding meal items, also an issue at https://uwaterloo.ca/food-services/menu (e.g. all Pastry Plus items link to the same incorrect product page)
I know the Open Data initiative cannot change the underlying data but would you be able to bring this up to the FoodServices team if possible?

**Comment by nathanv** [comment]
@alykhank on it. Thanks for reporting.

**Comment by nathanv** [comment]
@alykhank slight adjustment: we can change more than you think. For some time now I work closely with the Drupal WCMS team... and I do daily SCRUMS with the Drupal team.

**Comment by nathanv** [comment]
Reported issue upstream. Likely they will remove the links altogether like PAS lounge. I'm creating another ticket to get them to put in the data properly.

**Comment by alykhank** [comment]
Seems to have been fixed at some point, thanks!
