### ISSUE TITLE
[Food Services] Exception times are wrong

### ISSUE THREAD

**Issue by zachomedia** [uWaterloo/OpenData#165]
Hello,

I got a report that my site (https://zacharyseguin.ca/projects/you-want-food) was showing the wrong exception times. 

Examining the response from the API (foodservices/locations.json), it is returning the incorrect hours. They are 4 hours off which might be related to incorrect timezones. 

An example is Brubakers. The food services site shows it open from 10:00am-3:30pm on May 23rd, however the API is returning 2:00pm-7:30pm for May 23rd.

**Comment by nathanv** [comment]
@zachomedia I should be able to get this today.

**Comment by nathanv** [comment]
Assigning to Kartik but I'll steal it back tomorrow if he doesn't get to it.

**Comment by KartikTalwar** [comment]
I'll try and take to get to it tonight
ᐧ

**Comment by KartikTalwar** [comment]
This is now fixed.

**Comment by zachomedia** [comment]
@KartikTalwar I'm going to have to reopen this. Food services updated the times because their site was also showing the wrong times, and now the times returned by the API are ahead by 4 hours.

**Comment by KartikTalwar** [comment]
:(

**Comment by KartikTalwar** [comment]
Alright so, they did indeed fix the time but foodservices forgot to change the timezone therefore my correction that accounts for the timezone still fails on the input data

This is what the raw feed from foodservices looks like ![](http://i.imgur.com/rSBkgfS.png)

I'll ping them again on Monday to see if they can correct the timezones on their end. Reverting my changes temporarily now

**Comment by zachomedia** [comment]
@KartikTalwar Yeah, I was in contact with someone at Food Services the other day and the time were appearing wrong on their website which is why they changed them. I think this probably needs to be looked at with WCMS and Food Services (potentially WCMS is not converting times to Waterloo's timezone).

Just a reminder, Monday is a holiday so it'll have to wait till Tuesday.

Thanks for taking a look at this.

**Comment by KartikTalwar** [comment]
Right, forgot Monday is holiday. But yeah, the api is parsing the timezones from the given input correctly but updating the timezones was forgotten when they corrected the hours. The api currently is showing the correct time so on Tuesday i'll let foodservices know to update the timezones.

**Comment by zachomedia** [comment]
This is now fixed.
