### ISSUE TITLE
Missing Info Sessions for Spring Term

### ISSUE THREAD

**Issue by steviek** [uWaterloo/OpenData#166]

**Comment by nathanv** [comment]
Thank you for reporting. @steviek we'll look at this today.

**Comment by JoeRadman** [comment]
Let me know if find an error in the feed. I'm back next week. 

Thanks
Joe


Web design. Social media. 
Twitter: @joeradman

**Comment by KartikTalwar** [comment]
Hey @JoeRadman, looks like an issue on the feed from your end. No results are being returned for this term. Would next week be the only time you'll be able to look at this?

**Comment by JoeRadman** [comment]
I'll check it out tonight or tomorrow morning. 

:)

J


Web design. Social media. 
Twitter: @joeradman

**Comment by nathanv** [comment]
@JoeRadman Thanks!

**Comment by nathanv** [comment]
@steviek I just pinged @JoeRadman again and he said he'll get to a bit later this morning. Thank you for your patience :).

**Comment by JoeRadman** [comment]
Hi all

The feed was working - just an odd character in one of the descriptions.
I'm not certain what it was so I removed most of the text. Feed looks good
now for 1151.

Thanks
Joe




Joe Radman
University of Waterloo

**Comment by steviek** [comment]
I still don't think I'm getting anything for 1155 term though?

**Comment by nathanv** [comment]
@JoeRadman ?

**Comment by steviek** [comment]
This is still unresolved, any updates?

**Comment by JoeRadman** [comment]
I'll take another look - I think I resolved this a while back. I'll check
it now.

Joe



Joe Radman
University of Waterloo

**Comment by JoeRadman** [comment]
Should be OK now - there was an odd character in one of the sessions.
Here's the feed I believe you're using.

https://info.uwaterloo.ca/infocecs/students/sessions_open_data.php

Looks good now.

Let me know.

Thanks
Joe




Joe Radman
University of Waterloo
