### ISSUE TITLE
Scanners

### ISSUE THREAD

**Issue by jacktruong** [uWaterloo/OpenData#167]
Just thought a list of publicly available scanners would be a useful dataset to make available.

Engineering has 4 available to students and the [data is sparse but available on our website](https://uwaterloo.ca/engineering-computing/printing-and-scanning). I can send the co-op around to take note of which models they are too.

**Comment by nathanv** [comment]
@jacktruong Great idea! Feel free to get your team to do a pull request against https://github.com/uWaterloo/Datasets

**Comment by nathanv** [comment]
Closing as
