### ISSUE TITLE
Use new weather XML feed

### ISSUE THREAD

**Issue by TheUbuntuGuy** [uWaterloo/OpenData#168]
According to Frank at the UW weather station, the website is moving and the new XML feed is at http://www.civil.uwaterloo.ca/weather/waterloo_weather_station_data.xml

It is live now and will be the one updated in the future (the current XML feed has not been updating correctly for over a week now).

**Comment by nathanv** [comment]
Fixed! Thanks for reporting.

**Comment by nathanv** [comment]
@TheUbuntuGuy how come the new feed has both windchill and humidex active at the same time? that is weird!

**Comment by TheUbuntuGuy** [comment]
I just realized that too. I hope it goes back to the way it was before because it's difficult to determine which one to use at certain times of the year.

I've also noticed that it is only updating every 30 mins instead of 15 like it used to, although it still says to pull it at 5, 20, 35, and 50 past the hour. I'll talk to Frank and see what's going on.

**Comment by nathanv** [comment]
I've also noticed that http://www.civil.uwaterloo.ca/weather/ says the current reading for 2013 and then on the side it mentions 2017
Summary of today's readings
Summary of yesterday's readings point to weather.uwaterloo.ca instead of the civil server...

**Comment by TheUbuntuGuy** [comment]
They are moving the site while it's live, so I would expect some funny business. But that is pretty great.

**Comment by cdeange** [comment]
@nathanv I've noticed that `wind_direction_degrees ` is being reported as null in the current /weather/current endpoint. Is this related?

**Comment by kade-robertson** [comment]
This null `wind_direction_degrees` issue hasn't been addressed yet, it may have something to do with the feed XML returning the direction in N/S/E/W format instead of an actual degree number.

**Comment by zachomedia** [comment]
@cdeange @kade-robertson I've added a new property (`wind_direction`) which contains the wind direction reported in text format. The `wind_direction_degrees` will likely continue to be `null` as it's not provided by the XML feed.
