### ISSUE TITLE
BET 100 is not showing up when doing the query

### ISSUE THREAD

**Issue by Laxenade** [uWaterloo/OpenData#169]
"BET/100/schedule" will however show the result, but not "BET/100"

**Comment by Laxenade** [comment]
<BET/100/schedule> will however show the result, but not <BET/100>

**Comment by KartikTalwar** [comment]
@Laxenade can you update this description again - its a bit confusing to understand what you mean here

**Comment by Laxenade** [comment]
So basically, I was trying to retrieve the course information about BET 100, and I tried two ways:
1. "BET/100"
2. "BET/100/schedule"
The first way didn't return any data, but the second one did.

**Comment by zachomedia** [comment]
@Laxenade Thank you for reporting this, the data has now been updated and course information for BET 100 can now be retrieved from https://api.uwaterloo.ca/v2/courses/BET/100.json
