### ISSUE TITLE
Include location in the events feed

### ISSUE THREAD

**Issue by ostruk** [uWaterloo/OpenData#172]
Currently to get at which location the event is occurring, it is necessary to make a separate request to the events details end point. It would be useful to see at which location the event is occurring as part of the index of events:

https://api.uwaterloo.ca/v2/events/arts.json

Nate suggested to allow developers to select which fields they want to have included in the response.

Thanks!

**Comment by KartikTalwar** [comment]
Hey @ostruk, thanks for your feedback. Happy to announce that the events endpoint for a given site now includes the location object. The location key however will not be available for the global events feed: `/events.json`

**Comment by ostruk** [comment]
Thank you Kartik!
