### ISSUE TITLE
Awards values have a colon at the end

### ISSUE THREAD

**Issue by ostruk** [uWaterloo/OpenData#174]
https://api.uwaterloo.ca/v2/awards/undergraduate.json

Some entries have a colon at the end of the "value" field. E.g. "value": "$1200:"

Example award ids are: 470, 469, 461. The actual page for the award displays it fine:

https://uwaterloo.ca/student-awards-financial-aid/undergraduate-awards/mclenaghan-international-study-abroad-award

Also some awards don't have this issue, while in some cases it is appropriate (e.g. there's additional content after the column)

**Comment by zachomedia** [comment]
@ostruk This problem should now be fixed.
