### ISSUE TITLE
Program Graduate Requirement Open Data

### ISSUE THREAD

**Issue by yikkuro** [uWaterloo/OpenData#175]
It would be nice if a list of graduate requirements for different programs can be acquired.

**Comment by nathanv** [comment]
Hello @yikkuro ! Thank you for using the Open Data api and sending us feedback. We're currently [working on a brand new Graduate Studies Academic Calendar (GSAC)](https://uwaterloo.ca/web-resources/wcms-users/features-functionality/development-roadmap/gertrude-jan-11-feb-1).  It's due sometime in Q3-Q4 2016. As part of this effort, I'll see about ensuring that your requirement is brought in. If you're keen on Drupal you can track the code development work [here](gitlab@git.uwaterloo.ca:wcms/uw_ct_academic_calendar.git).

**Comment by SophieMJ** [comment]
I think he means if we can get the data for a list of graduate requirements for each undergraduate program. Undergrad calendar has those information, but it would be nice to have them as bulk data.
