### ISSUE TITLE
Request for uwParking space queue data.

### ISSUE THREAD

**Issue by steverweber** [uWaterloo/OpenData#178]
Request for uwParking space queue data.

Why?

Would like to apply some logic on finding out if Person A could trade spots with Person B.

**Comment by evisoup** [comment]
I don't think the parking lots spots are numbered or queued.

**Comment by kraigu** [comment]
They aren't numbered, but Parking Services certainly retains a wait list for individual lots, and knows who has been issued a pass for which lots. That said, they track tag # -> license plate/individual, so you're not likely trading spots without their involvement. It's possible that somebody (not me) could facilitate working with Parking on this though?

**Comment by evisoup** [comment]
OP should probably just build an app for trading the spots, using geo coordinates + driver provided car make&plate number to facilitate the trading (instead of using queue data)

**Comment by steverweber** [comment]
there is kinda an 'app' for trading spots.
https://uwaterloo.ca/parking/stafffaculty-permit-swapping

however as you can see it's underutilized and seems to be a flat webpage...

The idea is to build an app that uses the already large wealth of collected data. (many lots have more than 100 people in the queue.
