### ISSUE TITLE
available academic programs (data request)

### ISSUE THREAD

**Issue by DChang87** [uWaterloo/OpenData#179]

**Comment by nathanv** [comment]
Hello @DChang87 thank you for your request. Could you give me an idea of what sort of response you're looking for / what you're trying to build?

**Comment by DChang87** [comment]
Hello @nathanv , I'm looking for data regarding each program that UW offers (eg Computer Science, Math/CPA, Kinesiology, Mechanical Engineering). It'd be nice for each program to have a description, program size, tuition and other data that would interest potential undergraduates.

**Comment by nathanv** [comment]
Hello @DChang87 thank you for your inquiry. We've had a number of requests for program data. I'm currently in the midst of working with internal partners to get access to the data. I'll be sure to let you know when we have more progress.
