### ISSUE TITLE
Academic courses of term 1169 (along with start-end time, location etc for each section)

### ISSUE THREAD

**Issue by gCrew** [uWaterloo/OpenData#180]

**Comment by nathanv** [comment]
@gCrew , Thank you for your request. Are you asking for new data or for data that we provide regularly ?

**Comment by gCrew** [comment]
@nathanv I need a complete new data set for the current term only.
Thanks

**Comment by nathanv** [comment]
You can find all that data via https://api.uwaterloo.ca/v2/terms/1169/[subject]/schedule.json?key=[your key]
see docs: https://github.com/uWaterloo/api-documentation/blob/master/v2/terms/term_subject_schedule.md

**Comment by nathanv** [comment]
@gCrew did you get what you needed? If so, I'll go ahead an close this issue.

**Comment by gCrew** [comment]
Yup got what I wanted thanks. I will close the issue!
