### ISSUE TITLE
Endpoint for IST wifi-charts data

### ISSUE THREAD

**Issue by a1gemmel** [uWaterloo/OpenData#181]
I'd like to have endpoints for the [wifi-charts](https://uwaterloo.ca/information-systems-technology/statistics/wifi-charts) data that IST offers. I'm interested in doing some data analysis and building heatmaps for the data usage on campus.

**Comment by zachomedia** [comment]
Thanks @a1gemmel for the request. This is data we would like to have in the Open Data API, but I cannot offer an ETA at this time. Once I have more information regarding WiFi charts data, I'll let you know.

**Comment by srcreigh** [comment]
any updates here? :)

**Comment by zachomedia** [comment]
Hello @a1gemmel, @srcreigh and others:

I have a beta of the endpoints available now in the API. Documentation for the endpoints is still pending, but here's a quick highlight:

# Usage

Wireless usage information, updated every 15 minutes. Rates are reported in bits per second (bps).

- https://api.uwaterloo.ca/v2/wireless/usage.json
- https://api.uwaterloo.ca/v2/wireless/usage/{building_code}.json

# Clients

Returns a breakdown of clients who have connected to wireless. Groups are based on operating system and radio mode. This data is updated once daily.

- https://api.uwaterloo.ca/v2/wireless/clients.json

# Authentication Issues

This endpoint will return the number of authentication issues. The endpoint is currently unavailable.

- https://api.uwaterloo.ca/v2/wireless/auth.json

# Rogues

Returns the number of rogue access points detected. Data is updated every 15 minutes.

- https://api.uwaterloo.ca/v2/wireless/rogues.json

# Historical Data

All endpoints also have a separate endpoint to fetch historical data. Data is available for the past 30 days (number of days to retain has not been finalised).

All historical endpoints have two mandatory query string parameters: `from` and `to`. These are date/time values provided in ISO 8601 format (`YYYY-MM-DD` or `YYYY-MM-DDThhmmss(+|-)hhmm`).

- https://api.uwaterloo.ca/v2/wireless/historical/usage.json
- https://api.uwaterloo.ca/v2/wireless/historical/usage/{building_code}.json
- https://api.uwaterloo.ca/v2/wireless/historical/clients.json
- https://api.uwaterloo.ca/v2/wireless/historical/rogues.json

---

There are some known issues that occasionally result in stale data. Let me know if you experience any issues or have any comments/feedback.

**Comment by KartikTalwar** [comment]
woo!

**Comment by zachomedia** [comment]
Full documentation is now available: https://github.com/uWaterloo/api-documentation#wireless
