### ISSUE TITLE
examschedule doesn't work?

### ISSUE THREAD

**Issue by z687wang** [uWaterloo/OpenData#182]
Anyone can help? Server side error?

**Comment by zachomedia** [comment]
@z687wang Is there a specific course that it's failing for? I've checked a few and exam schedules come back as expected.

**Comment by z687wang** [comment]
@zachomedia it seems that they all work fine perhaps it was my internet issue before. By the way , Can we get computer labs information such as inuse number ? Thanks.

**Comment by zachomedia** [comment]
@z687wang Computer lab information is not currently in the Open Data API, but it something we are looking to add.
