### ISSUE TITLE
InfoSessions Time Zone

### ISSUE THREAD

**Issue by kade-robertson** [uWaterloo/OpenData#183]
Currently, the `/resources/infosessions` endpoint returns the day, the day of week, the start time and the end time of the info session. However, unlike some other sources, there is no time zone information included. This makes localization and time conversion a bit tricky when considering daylight savings and the like, so having a raw date-time string like what is provided with the GooseWatch endpoint among others would be useful. To avoid breaking backwards compatibility, two new entries called `start_time_full` and `end_time_full` (or something along those lines) could be added.

**Comment by JoeRadman** [comment]
Thanks - I'll look into that and make the changes. 


Joe Radman

**Comment by kade-robertson** [comment]
Great, thanks. Is it also possible to implement this for the `/terms/{term}/examschedule` endpoint? Specifically, the list containing each section for a class follows the same time format as `/resources/infosessions` does and likely could have the same solution applied.

**Comment by axyjo** [comment]
@JoeRadman This would be easily fixed with #156

**Comment by sbobkin** [comment]
Closing as this is v2 related, and it's no longer available.
