### ISSUE TITLE
Opportunities - seem missing from Student Success

### ISSUE THREAD

**Issue by JoeRadman** [uWaterloo/OpenData#185]
Hi,

The student success office has these opportunities:
https://uwaterloo.ca/student-success/opportunities/join-global-engagement-leadership-program-gelp-fall-2017
https://uwaterloo.ca/student-success/opportunities/international-orientation-volunteer

I can't find them in the JSON feed. Can you have a look? Are all opportunities from all WCMS sites automatically included in the feed?

Thanks
Joe

**Comment by zachomedia** [comment]
Hi Joe,

I've forced an update of the Student Success opportunities in Open Data and now the two opportunities appear.

I'll have to investigate why they weren't there and if this affects others WCMS sites as well.

Thanks,

Zachary Seguin

**Comment by JoeRadman** [comment]
Thanks Zac
