### ISSUE TITLE
Employer Information Sessions are not working for Fall 2017 term

### ISSUE THREAD

**Issue by vishalshubham** [uWaterloo/OpenData#187]
Tried using https://api.uwaterloo.ca/v2/terms/1179/infosessions.json?key=[api_key] to pull Fall 2017 information sessions but it return "No data returned".

Can you check and let me know if I am doing anything wrong.

**Comment by zachomedia** [comment]
@vishalshubham Thanks for reporting the issue. I've implemented a fix in the API, and Information Sessions for the Fall 2017 are now returned by the API.

Let me know if you experience any other issues.
