### ISSUE TITLE
Food services data missing locations

### ISSUE THREAD

**Issue by jmccarth** [uWaterloo/OpenData#190]
When querying [the foodservices geojson endpoint](https://api.uwaterloo.ca/v2/foodservices/locations.geojson) only a few of the food services locations are reporting locations anymore. The rest have 0,0 as coordinates now. The effects can be seen on the campus map. It would be nice if this were to be fixed before orientation.

Forgot to mention that I first noticed this late last week if that helps track it down.

**Comment by jemcclin** [comment]
Ticket has been filed with WCMS to resolve the error with the underlying data (RT641950). Looks like it's on the roadmap to be resolved with the 2.6.0 release.

**Comment by kpaxman** [comment]
Yes, we're working on it now. A security update broke location feeding, we're trying to fix it without removing the security update.

**Comment by sbobkin** [comment]
Closing as this is v2 related, and it's no longer available.
