### ISSUE TITLE
Internal Server Error / No Data Returned for /parking/watpark

### ISSUE THREAD

**Issue by hugo00618** [uWaterloo/OpenData#194]
/parking/watpark API is not working.

json file returned:
`{"meta":{"requests":481,"timestamp":1531330553,"status":204,"message":"No data returned","method_id":1823,"method":{}},"data":[]}`

**Comment by sbobkin** [comment]
The underlying service API that serves the parking lot sensor data was offline. That service is now restored, we're waiting to see updated data. However, the endpoint for OpenData should return data shortly. 

Thanks for the report!
