### ISSUE TITLE
Is there a way to query course anti-requisites?

### ISSUE THREAD

**Issue by cyamonide** [uWaterloo/OpenData#198]
Similar to the [Course Prerequisites](https://github.com/uWaterloo/api-documentation/blob/master/v2/courses/subject_catalog_number_prerequisites.md) endpoint, is there one for course anti-requisites?

If not, could this functionality be added?

**Comment by sbobkin** [comment]
Hi @cyamonide 
There is not. 

The longer answer is the current implementation relies on parsing string text and is not always accurate. There are several on going efforts across Waterloo to use the actual codified data for this information, but at this time they're not complete and with no clear path into open data.
