### ISSUE TITLE
Incorrect Response from /v2/terms/list

### ISSUE THREAD

**Issue by marktdodds** [uWaterloo/OpenData#200]
When you hit the endpoint `/v2/terms/list.json` with a valid request, the following data is returned for `listings`:

```json
"listings": {
            "2018": [
                {
                    "id": 1181,
                    "name": "Winter 2018"
                },
                {
                    "id": 1185,
                    "name": "Spring 2018"
                },
                {
                    "id": 1189,
                    "name": "Fall 2018"
                }
            ],
            "2019": [
                {
                    "id": 1191,
                    "name": "Winter 2019"
                },
                {
                    "id": 1195,
                    "name": "Spring 2019"
                },
                {
                    "id": 1199,
                    "name": "Fall 2019"
                }
            ],
            "2020": [
                {
                    "id": 1101,
                    "name": "Winter 2010"
                },
                {
                    "id": 1105,
                    "name": "Spring 2010"
                },
                {
                    "id": 1109,
                    "name": "Fall 2010"
                }
            ]
        }
```

Obviously the entries in `2020` should be from 2010.

Note: the xml version of the endpoint `/v2/terms/list.xml` also returns the same incorrect information.

**Comment by sbobkin** [comment]
Hi, 

Thanks for reporting this. I apologize this response has taken time as I was away. Terms data has an authoritative source, and as such it's one of the data sets we've implemented from the source system in the new version. 

While we may fix this as reported in v2 (unlikely), I would suggest reading this post https://wiki.uwaterloo.ca/display/UWAPI/2018/09/06/Open+Data+vNext+Available+and+Update and the associated getting started page https://wiki.uwaterloo.ca/display/UWAPI/Getting+Started+-+OpenAPI to get the current and future term data from the new version of the API.

**Comment by sbobkin** [comment]
I'm going to close this issue. There's been a delay, but fundamentally the guidance remains the same, you should use the Terms endpoint on v3: https://openapi.data.uwaterloo.ca/api-docs/index.html 

It has accurate, authoritative data.
