### ISSUE TITLE
Unable to request for API key

### ISSUE THREAD

**Issue by ZacJoffe** [uWaterloo/OpenData#202]
It seems as if I can't request an API key for v3 on the official Open Data API [page](https://uwaterloo.ca/api/).

As noted in #199, the wiki seems to be only accessible on the campus network. I'm currently on coop outside of Waterloo, so if there is any information about this on the wiki I don't have access to it.

**Comment by sbobkin** [comment]
Hi, yes, the documentation is currently only accessible on campus or by using the VPN service. For the purpose of the getting started, I've copied the content to the GitHub wiki page [here](https://github.com/uWaterloo/OpenData/wiki/Home---Getting-Started).
