### ISSUE TITLE
Latitudes and Longitudes are flipped in Locations/geojson endpoint

### ISSUE THREAD

**Issue by jmccarth** [uWaterloo/OpenData#207]
The `/v3/Locations/geojson` endpoint returns geojson with the x and y coordinates in the wrong order as part of the geometry definition.

```json
{"type":"Feature","properties":{"buildingId":"57","buildingCode":"EV3","parentBuildingCode":null,"buildingName":"Environment 3","alternateBuildingNames":null,"latitude":43.468159,"longitude":-80.543376},"geometry":{"type":"Point","coordinates":[43.468159,-80.543376]}}
```

GeoJSON expects the coordinates to be in x, y order (which is longitude, latitude), but the returned value is in y, x order (latitude, longitude).

This results in the locations appearing like this (using geojson.io as an example):
![image](https://user-images.githubusercontent.com/1231175/96165170-45232780-0eea-11eb-9936-b9dc1e809aa7.png)

**Comment by sbobkin** [comment]
@jmccarth I believe this is resolved now; can you confirm please?

**Comment by jmccarth** [comment]
@sbobkin Yep, that did the trick. Looks good now. Thanks.

**Comment by sbobkin** [comment]
Good to hear @jmccarth let me know if you find any other issues while you make the transition.
