### ISSUE TITLE
Instructor names

### ISSUE THREAD

**Issue by BobscHuang** [uWaterloo/OpenData#211]
Will instructor names no longer be available in v3 of the api? Or is this something that will be added later down the line?

**Comment by sbobkin** [comment]
@BobscHuang we've reached out to the data steward to see if this data can be added. There has been a push to limit programmatic and access in general to what is personal/private data.

**Comment by sbobkin** [comment]
This came up in another issue and I've provided more responses there, closing this one as duplicate of https://github.com/uWaterloo/OpenData/issues/215
