### ISSUE TITLE
v3 exam schedule

### ISSUE THREAD

**Issue by amward-uwaterloo** [uWaterloo/OpenData#212]
Are there plans for the exam schedule data to be added to the v3 API?

I am building an app to accommodate 2FA for exams held in controlled computer labs on campus.

Thanks,
Andrew

**Comment by sbobkin** [comment]
I was under the impression that data is not going to be published anymore on the source page with online learning taking place. That is largely why we did not re-implement this. I looked now and that may be incorrect, let me try to follow up on this.

**Comment by amward-uwaterloo** [comment]
Thanks Sergey,

I don't think it's really required until exams are happening again in person. I will need it at that point, though. Know roughly what the data will look like would be good so I can get development done in advance would be helpful.

Andrew

**Comment by sbobkin** [comment]
The exam schedule information is now back and available in the v3 API. See the blog post for additional information: https://wiki.uwaterloo.ca/display/UWAPI/2021/07/20/Open+Data+v3+2021.07.20.1+release 

I expect the schema to remain fairly consistent going forward, but if UW makes fundamental changes to how classes are offered and exam schedules are released we may need to make updates.
