### ISSUE TITLE
Limits and sorting on WCMS endpoints

### ISSUE THREAD

**Issue by ebremner17** [uWaterloo/OpenData#213]
Can we please get limits and sorting on WCMS endpoints for news, events and blogs for WCMS, so something like v3/Wcms/{siteId}/news.  A site like engineering returns 1216 results and takes a long time to load.  It would also be nice to be able to sort on postedDate so that you are getting the latest news first.

**Comment by sbobkin** [comment]
@ebremner17 there is now a query parameter option to limit the result set, and an option to return newest item first. By default, but not guaranteed, the results will be sorted now also.
