### ISSUE TITLE
Missing {pre,co,anti} requisite data

### ISSUE THREAD

**Issue by andythsu** [uWaterloo/OpenData#214]
Hello,
I don't know if I'm missing anything, but I don't seem to find course {pre,co,anti} requisite data anymore on v3 like what v2 used to have. I'd expect to find those data in Courses endpoint but I don't find any. Is this still WIP or it's in somewhere else?

**Comment by sbobkin** [comment]
Hi @andythsu 

The information is available under the "requirementsDescription" property from the Courses endpoint(s). 
For example, you can see it for ACTSC 371 in the 1209 term: https://openapi.data.uwaterloo.ca/v3/courses/1209/ACTSC/371

We no longer explicitly break out the requirements as that relied on string parsing in the version 2 of the API which was error prone. Delivering that functionality as is would break our stance that this data is accurate as in the source authoritative system. 

The detailed requirements information does exist in Quest, and we may try to add it at a later date. However, I have no ETA, and from past experiences the requirement description and the actual requirement rules sometimes do not match.

**Comment by andythsu** [comment]
> Hi @andythsu
> 
> The information is available under the "requirementsDescription" property from the Courses endpoint(s).
> For example, you can see it for ACTSC 371 in the 1209 term: https://openapi.data.uwaterloo.ca/v3/courses/1209/ACTSC/371
> 
> We no longer explicitly break out the requirements as that relied on string parsing in the version 2 of the API which was error prone. Delivering that functionality as is would break our stance that this data is accurate as in the source authoritative system.
> 
> The detailed requirements information does exist in Quest, and we may try to add it at a later date. However, I have no ETA, and from past experiences the requirement description and the actual requirement rules sometimes do not match.

Good to know the data is still provided! I knew I missed it somewhere.  Thank you!
