### ISSUE TITLE
Request for instructor name in InstructorData

### ISSUE THREAD

**Issue by edwinzhng** [uWaterloo/OpenData#215]
Hi! I was trying to query for ClassSchedules using the API via the [live documentation](https://openapi.data.uwaterloo.ca/api-docs/index.html), but every time I tried to hit the `​/v3​/ClassSchedules​/{termCode}​/{courseId}`, or the `/v3/ClassSchedules/{termCode}/{subject}/{catalogNumber}` endpoints, it returns a 404 response. I double checked that these courses were in fact listed when I query for `/v3/Courses`, so I'm not sure if there is an error with the service when returning the schedules. 

For example, the course ECE 103 is listed when I query for `/v3/Courses/1215/ECE`, but when I try to query `/v3/ClassSchedules/1215/ECE/103`, I get a 404. 

Any help would be appreciated!

**Comment by edwinzhng** [comment]
Thanks, that makes sense! I just had two more questions:

1. I noticed that compared to the v2 API, we are no longer able to access instructor names for each of the courses. Is there any plan to add this back or would this be possible?

The reason I'm asking is because I'm doing a (very late) migration of `uwflow.com`[https://uwflow.com] to import data from the new API version, and we rely on the instructor names to populate our schedules.

2. Is there any API rate limit I should be aware of? We were planning to re-import schedule data for each course approximately every hour, which would be a couple thousand requests. If this is an issue, I could dial it back a bit.

**Comment by sbobkin** [comment]
A1.  I did not hear back from the data stewards about introducing this data back in; I'll follow up today/tomorrow. 
A2. No rate limit, no plan to rate limit. If you're seeing performance issues please do let us know.

**Comment by edwinzhng** [comment]
Ok sounds great, thanks a lot for the help!

**Comment by edwinzhng** [comment]
Hey @sbobkin, just wondering if you might have any updates regarding the instructor name data for class schedules?

**Comment by sbobkin** [comment]
@edwinzhng entirely with the data steward/Registrar's Office to get an answer if they're okay with this or not. We've asked for an update, but I don't have an agreement from them, so we can't add it yet.

**Comment by sbobkin** [comment]
Sorry, no update, it may be of value to reach out to Dave Bean at the Registrar Office directly and indicate your desire to have this information in the Open Data API.

**Comment by sbobkin** [comment]
As an update, we have approval to add this data to the endpoint. I don't have an ETA yet, but sometime in September is likely.

**Comment by edwinzhng** [comment]
Awesome, thanks so much for the update

**Comment by sbobkin** [comment]
Hi, 

I've published a new release, you can see the changes here: https://wiki.uwaterloo.ca/display/UWAPI/2021/09/16/Open+Data+API+v3%2C+2021.09.16.1+release

This adds instructor name, and an identifier information to the class schedules endpoint.

**Comment by edwinzhng** [comment]
Perfect thanks for all the help, I will try the new data next week!

**Comment by edwinzhng** [comment]
Hi @sbobkin, it seems like the API is returning 500 responses for `​/v3​/ClassSchedules​/{termCode}​/{subject}​/{catalogNumber}` - for example /v3​/ClassSchedules​/1219​/ECE​/105 should have scheduled sections according to ADM, and `v3/Courses/1219/ECE/105` returns course data properly, so maybe this was due an error in the new release? Let me know if you need any more details on this

**Comment by sbobkin** [comment]
@edwinzhng thank you for reporting, with apologies, this should be fixed.

**Comment by edwinzhng** [comment]
Worked, thanks! Closing this issue since everything seems good
