### ISSUE TITLE
Past term data

### ISSUE THREAD

**Issue by q225yang** [uWaterloo/OpenData#216]
Hi,

My name is Ethan Yang and I am a 3B data science student from UW. I requested some past data about class schedules and courses information for my CS project this term. The data was provided and it helped, but there were some tiny issues about the data (the data were provided separately and the primary keys are ambiguous so I find it hard to join the information). Also, the project requires us to provide the methods to get the real world data instead of submitting the data itself. So I wonder if it is possible that I can get the access of part of the data maybe with some API key. I only need parts of the data and the access for about one month until the project is presented. If this is not applicable, then can I get a new version of data? Thanks for your time and consideration in advance.

Kind regards,

Ethan

**Comment by sbobkin** [comment]
Hi Ethan, 

There is no plan or intent at this time to provide historic data outside of the past, current, next term range the API provides now. I can help you join the data extract you received; CourseId+Term+ClassNumber+Session is the most complete join key, or CourseId+Term+ClassNumber where available. 

Your app can perhaps read the extract files as a local database?

**Comment by q225yang** [comment]
Hi Sbobkin,

I have attached two screen shots of class schedule as an instance. These two screen shot come from different sheets of one Excel file that I received. However, I can’t see the join key you described. I have also attached the file ``1201 CS and Math subject schedules.xlsx`` that I received.

As for ``1201 Class Locations.xlsx``, I can join the locationName based on TermCode+ClassNumber+ClassSection+ClassMeetingNumber.

[Graphical user interface, application, table, Excel  Description automatically generated]
[Table  Description automatically generated with low confidence]

From: sbobkin ***@***.***>
Date: Monday, July 5, 2021 at 8:56 AM
To: uWaterloo/OpenData ***@***.***>
Cc: Ethan Yang ***@***.***>, Author ***@***.***>
Subject: Re: [uWaterloo/OpenData] Past term data (#216)

Hi Ethan,

There is no plan or intent at this time to provide historic data outside of the past, current, next term range the API provides now. I can help you join the data extract you received; CourseId+Term+ClassNumber+Session is the most complete join key, or CourseId+Term+ClassNumber where available.

Your app can perhaps read the extract files as a local database?

**Comment by sbobkin** [comment]
@q225yang for course and schedules you can use CourseId, CourseOfferNumber, Term. To add the separate locations extract you can use TermCode (same as Term)+CourseId+ClassNumber (also ClassNumber in Course and Capacity sheet).
