### ISSUE TITLE
locationName field for ClassSchedules doesn't contain correct information

### ISSUE THREAD

**Issue by edwinzhng** [uWaterloo/OpenData#221]
Hi, it seems like the `locationName` field for the `ClassSchedules` endpoint only returns the name of the term, eg) "Winter 2022". Would it be possible to update this to list the actual location + building or if the class is online? For example, MATH 135 has locations listed on ADM as `MC 4041`, `PHY 150`, and `Online`:

<img width="1206" alt="Screen Shot 2021-11-17 at 3 42 38 PM" src="https://user-images.githubusercontent.com/21136804/142221763-099a38b8-1979-4470-aad8-14d495ba5614.png">

**Comment by sbobkin** [comment]
Hi, 

Thank you for reporting. We've reached out to the stewards about this last week. I don't have an answer yet other then we believe the field use changed a bit with online/in-class learning. We'll update this with a fix as soon as we have an answer from the data stewards.

**Comment by sbobkin** [comment]
@edwinzhng this has been fixed.

**Comment by edwinzhng** [comment]
Awesome thank you for the quick turnaround!
