### ISSUE TITLE
ImportantDates missing data

### ISSUE THREAD

**Issue by jacktruong** [uWaterloo/OpenData#225]
The v3/ImportantDates endpoint is missing data in details, keywords, and audiences. All entries are currently displaying empty array objects or null.

 ```
[
  {
    "id": 1,
    "name": "Co-operative work term begins",
    "description": "<p>Actual dates may vary depending on employer or student requirements.</p>\n",
    "importantDateType": "Academic",
    "details": [],
    "keywords": null,
    "audiences": null
  },
...
 {
    "id": 334,
    "name": "University holiday closure",
    "description": "<p>No classes and offices closed.</p>\n",
    "importantDateType": "University closure",
    "details": [],
    "keywords": null,
    "audiences": null
  }
]
```

**Comment by sbobkin** [comment]
This should be resolved as of now. There was new data that was far enough in the future that caused an issue in an update as of yesterday. Can you confirm on your end?

**Comment by jacktruong** [comment]
Confirmed the bug is fixed and my apps are working again. Thanks
