### ISSUE TITLE
/v3/account/notify and /v3/account/register not sending email

### ISSUE THREAD

**Issue by jerryzhou196** [uWaterloo/OpenData#227]
Hello there, hope all is well.

I'm trying to request an API key with my alternate waterloo email (jerry.zhou@uwaterloo.ca) after Swagger reported that my other email j448zhou@uwaterloo.ca was already registered. I'm not sure if I did this a while back with the j448zhou@uwaterloo.ca email but never got to using it, but I couldn't find any email sent to my inbox sadly regarding an API key or confirmation, and any attempts to use the /v3/account/register and /v3/account/notify don't seem to send an email to my inbox despite a successful response code with my alternative jerry.zhou@uwaterloo.ca email.

**Comment by sbobkin** [comment]
Can you let me know if you received an email, or get one shortly? I believe I've addressed the issue.

**Comment by jerryzhou196** [comment]
Received an email and resolved. Thanks so much mate!
