### ISSUE TITLE
University of Waterloo Stress Dataset (UWS)

### ISSUE THREAD

**Issue by samson220** [uWaterloo/OpenData#228]

**Comment by samson220** [comment]
Good day,
My name is Samson Mihirette, a PhD student working on stress detection and I would like to get access to the "University of Waterloo Stress Dataset (UWS)".
Can you please help? My email address: uo298476@uniovi.es
thank you.

**Comment by sbobkin** [comment]
Hi @samson220  

At this time we don't have a "stress dataset" modeled for public consumption. Given the challenges around what a properly anonymized dataset of that nature would be, it is unlikely this is something the Open Data project will take on as is.
