### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by mrahroy** [uWaterloo/OpenData#229]
Hello respected Sir,I hope this email finds you well.I am a student of MSc AI at MTU, Cork, Ireland. I have been looking at your work related to the stress. I have come across two dataset names i.e. "University of Waterloo Stress Dataset (UWS)" and "Multi-Modal Stress Dataset (MMSD)" .I am carrying out my thesis work on the same subject i.e. stress classification and prediction. Aforesaid, if possible, I request you to please share the consolidated dataset used in your study with me so that I could use it in my thesis.Looking forward to hearing from you.
Best regards,
Ahmed

**Comment by sbobkin** [comment]
Hi, 

I'm not aware of such a dataset being publicly available. It's at best a research dataset and not covered in the intent to share for this Open Data API. 

Thank you for your interest.
