### ISSUE TITLE
`/v3/importantDates` is missing data

### ISSUE THREAD

**Issue by jerryzhou196** [uWaterloo/OpenData#230]
EDIT: The original issue was not correct so I updated it. 

Currently, UWFlow uses the `/v3/ImportantDates` endpoint to get the exact startDate and endDate for all terms, as the `/v3/Terms` endpoint only provides hardcoded dates and the internal logic requires that we have the specific start and end dates for every term. However, it seems the data for the upcoming term is no longer being updated in the `/v3/importantDates` endpoint. One example in particular is the "Classes Begin" event for the upcoming terms on September 4th, 2024, which is shown on https://uwaterloo.ca/registrar/important-dates/calendar but not on the endpoint  (contains data only up to May 2024) . 

![image](https://github.com/user-attachments/assets/94112093-68e9-416a-a689-911ddde8ef22)

![image](https://github.com/user-attachments/assets/7734c4ef-f134-4712-bd76-afdc660e342d)

**Comment by sbobkin** [comment]
I'll take a look at the important dates data; ETA is next week. 

To clarify a few things about the term data which may help you. 

The "Terms" endpoint is the official start and end date of the Term according to Quest/RO. The classes begin date, which you're looking for is a different event and why they don't line up. 

Technically, you probably want to be looking at the schedule start and end dates within the "Class Schedule" data as there is not a reason a class schedule could not start later, less likely to be earlier, than the classes begin date.

**Comment by sbobkin** [comment]
The issue with missing important dates is now resolved; there was a part of a refresh that wasn't happening. 

As a heads up, when looking into this I found that the data is migrating August 27th, there may be some interruption at that date for this data again. I'll try to internally find out what's happening, but we were not previously aware.

**Comment by jerryzhou196** [comment]
You are the unsung hero of Waterloo, friend. Thanks so much for looking into this and fixing it.
