### ISSUE TITLE
Access to Authenticated WatIAM Whitepages

### ISSUE THREAD

**Issue by cnvandev** [uWaterloo/OpenData#29]
Love the open data initiatives going on! Always good to see this kind of stuff opening up, it's perfect for devs like me :)

I'm EngFOC for 2013 and I'm working on the website we use to manage various bits of data that we use. I have our website (http://engfoc.uwaterloo.ca/) authenticated via CAS which has been a _huge_ help in streamlining our application forms - now we don't need our leaders to manually type in their user IDs, we don't need to search for typos, we don't need to check if people forgot to type in IDs...it's a great addition.

It would be a huge help, however, to be able to map that back to real names somehow. The easiest way would be WatIAM, so even people who didn't apply to be leaders would still be able to work with the authenticated portions of the website (and there are a number of people who fall under this list). We could easily, for example, bring up all of the leaders who are in Software Engineering, because they can have extra responsibilities (there's a Software Engineering directorship, etc.) I just looked at #26 and see that there's LDAP access for this, which I'll investigate, but a straight WatIAM (like what's at http://watiam.uwaterloo.ca) would be perfect.

I know this gets into authenticated-API-territory, and there are already tickets for that (#23) so I won't add to them, but definitely consider this a strong vote for that being a priority :)

**Comment by phileverson** [comment]
@KartikTalwar Looking to use LDAP to authenticate into an installation of [Confluence](https://www.atlassian.com/software/confluence) I'm running for [EntSoc](http://www.entsoc.ca). Is any of this still relevant? Namely your [sample code](https://github.com/uWaterloo/OpenData/issues/29#issuecomment-14633423)?

**Comment by KartikTalwar** [comment]
yes, the code still works but only if your IP is on campus
