### ISSUE TITLE
KPI endpoint

### ISSUE THREAD

**Issue by axyjo** [uWaterloo/OpenData#78]
Can we get stats from https://uwaterloo.ca/performance-indicators/ as an API endpoint?

**Comment by axyjo** [comment]
Any updates?

**Comment by axyjo** [comment]
Bump.

**Comment by nathanv** [comment]
@axyjo 
The data is now available via CSVs on the website. Every KPI has a section entitled "Data Table" and a csv is available for use.

**Comment by axyjo** [comment]
Awesome. Thanks!
